### ISSUE TITLE
Nuxt.js Error

### ISSUE THREAD

**Issue by kodekrendel** [esclapes/coosto-hackathon#1]
Hi.

Will appreciate if you explain. I am trying to run it on mu Ubuntu but got error.

In browser:

```
Nuxt.js Error:

/home/qman/Desktop/NUXT/GRAPHQL/coosto-hackathon/app/node_modules/vue2-google-maps/dist/components/infoWindow.vue:3
<template>
^
SyntaxError: Unexpected token <
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/qman/Desktop/NUXT/GRAPHQL/coosto-hackathon/app/node_modules/vue2-google-maps/dist/main.js:39:19)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
```
In console

```
WARNING  Compiled with 2 warnings                                    8:46:44 PM

 warning  in ./pages/index.vue

(Emitted value instead of an instance of Error) <gmap-marker v-for="m in places">: component lists rendered with v-for should have explicit keys. See https://vuejs.org/guide/list.html#key for more info.

 @ ./pages/index.vue 9:2-201
 @ ./.nuxt/router.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi webpack-hot-middleware/client?reload=true ./.nuxt/client.js

 warning  in ./pages/location/_id.vue

(Emitted value instead of an instance of Error) <gmap-marker v-for="m in dogPlace.nearby">: component lists rendered with v-for should have explicit keys. See https://vuejs.org/guide/list.html#key for more info.
```

**Comment by alexjoverm** [comment]
I believe this has something to do with a newer version of Nuxt, lot's of things have changed since we made this. There is an issue related to this https://github.com/nuxt/nuxt.js/issues/438

I'll try to fix it when I find some time

**Comment by alexjoverm** [comment]
@kodekrendel everything should be fine now. The project went a bit out of date due to how fast nuxt changed.

If you look at the latest commits you'll see the details, but in short:

 - I had to exclude vue2-google-maps from externals in the webpack config. It seems now nuxt adds everything to externals on the server build, and vue2-google-maps is not in a compiled JS or ESM format
 - The method `data` has been split in `data` and `asyncData` for pages since version 0.10.6

**Comment by kodekrendel** [comment]
@alexjoverm thanks for update! Will check it out later today. (Dog Shit this is hilarious :smiley: )
